/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { VotingSystem } from "./VotingSystem";
export * as factories from "./factories";
export { VotingSystem__factory } from "./factories/VotingSystem__factory";
