/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export type VotingInfoStruct = {
  id: BigNumberish;
  title: string;
  startTime: BigNumberish;
  endTime: BigNumberish;
  metaCID: BytesLike;
  propositions: BytesLike[];
  votingType: BigNumberish;
};

export type VotingInfoStructOutput = [
  id: bigint,
  title: string,
  startTime: bigint,
  endTime: bigint,
  metaCID: string,
  propositions: string[],
  votingType: bigint
] & {
  id: bigint;
  title: string;
  startTime: bigint;
  endTime: bigint;
  metaCID: string;
  propositions: string[];
  votingType: bigint;
};

export declare namespace VotingSystem {
  export type VotingInfoWithChoiceStruct = {
    id: BigNumberish;
    title: string;
    startTime: BigNumberish;
    endTime: BigNumberish;
    metaCID: BytesLike;
    propositions: BytesLike[];
    votingType: BigNumberish;
    choice: BytesLike;
  };

  export type VotingInfoWithChoiceStructOutput = [
    id: bigint,
    title: string,
    startTime: bigint,
    endTime: bigint,
    metaCID: string,
    propositions: string[],
    votingType: bigint,
    choice: string
  ] & {
    id: bigint;
    title: string;
    startTime: bigint;
    endTime: bigint;
    metaCID: string;
    propositions: string[];
    votingType: bigint;
    choice: string;
  };
}

export interface VotingSystemInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addAdmin"
      | "addAdmin(address)"
      | "addVoter"
      | "addVoter(address)"
      | "admins"
      | "admins(address)"
      | "chairman"
      | "chairman()"
      | "createVoting"
      | "createVoting(string,uint256,uint256,uint8,bytes32,bytes32[])"
      | "getActiveVotings"
      | "getActiveVotings(uint256,uint256)"
      | "getCompletedVotings"
      | "getCompletedVotings(uint256,uint256)"
      | "getIncomingVotings"
      | "getIncomingVotings(uint256,uint256)"
      | "getPropositions"
      | "getPropositions(uint256)"
      | "getRole"
      | "getRole(address)"
      | "getVoting"
      | "getVoting(uint256)"
      | "getVotingBatch"
      | "getVotingBatch(uint256[])"
      | "getVotingHistory"
      | "getVotingHistory(address,uint256,uint256)"
      | "getVotingStats"
      | "getVotingStats(uint256)"
      | "getVotingStatus"
      | "getVotingStatus(uint256)"
      | "removeAdmin"
      | "removeAdmin(address)"
      | "removeVoter"
      | "removeVoter(address)"
      | "vote"
      | "vote(uint256,uint256)"
      | "voters"
      | "voters(address)"
      | "votingCount"
      | "votingCount()"
      | "votings"
      | "votings(uint256)"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "VoteCast"
      | "VoteCast(address,uint256,uint256)"
      | "VotingCreated"
      | "VotingCreated(uint256,string,uint8)"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addAdmin",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "addAdmin(address)",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "addVoter",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "addVoter(address)",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "admins", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "admins(address)",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "chairman", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "chairman()",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "createVoting",
    values: [
      string,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BytesLike,
      BytesLike[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "createVoting(string,uint256,uint256,uint8,bytes32,bytes32[])",
    values: [
      string,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BytesLike,
      BytesLike[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getActiveVotings",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getActiveVotings(uint256,uint256)",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getCompletedVotings",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getCompletedVotings(uint256,uint256)",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getIncomingVotings",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getIncomingVotings(uint256,uint256)",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPropositions",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPropositions(uint256)",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRole",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getRole(address)",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getVoting",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getVoting(uint256)",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getVotingBatch",
    values: [BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "getVotingBatch(uint256[])",
    values: [BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "getVotingHistory",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getVotingHistory(address,uint256,uint256)",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getVotingStats",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getVotingStats(uint256)",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getVotingStatus",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getVotingStatus(uint256)",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "removeAdmin",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "removeAdmin(address)",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "removeVoter",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "removeVoter(address)",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "vote",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "vote(uint256,uint256)",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "voters", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "voters(address)",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "votingCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "votingCount()",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "votings",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "votings(uint256)",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "addAdmin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "addAdmin(address)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "addVoter", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "addVoter(address)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "admins", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "admins(address)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "chairman", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "chairman()", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createVoting",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createVoting(string,uint256,uint256,uint8,bytes32,bytes32[])",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getActiveVotings",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getActiveVotings(uint256,uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCompletedVotings",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCompletedVotings(uint256,uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getIncomingVotings",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getIncomingVotings(uint256,uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPropositions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPropositions(uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getRole(address)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getVoting", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getVoting(uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getVotingBatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getVotingBatch(uint256[])",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getVotingHistory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getVotingHistory(address,uint256,uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getVotingStats",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getVotingStats(uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getVotingStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getVotingStatus(uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeAdmin(address)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeVoter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeVoter(address)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "vote", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "vote(uint256,uint256)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "voters", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "voters(address)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "votingCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "votingCount()",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "votings", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "votings(uint256)",
    data: BytesLike
  ): Result;
}

export namespace VoteCastEvent {
  export type InputTuple = [
    voter: AddressLike,
    votingId: BigNumberish,
    propositionIndex: BigNumberish
  ];
  export type OutputTuple = [
    voter: string,
    votingId: bigint,
    propositionIndex: bigint
  ];
  export interface OutputObject {
    voter: string;
    votingId: bigint;
    propositionIndex: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VotingCreatedEvent {
  export type InputTuple = [
    votingId: BigNumberish,
    title: string,
    votingType: BigNumberish
  ];
  export type OutputTuple = [
    votingId: bigint,
    title: string,
    votingType: bigint
  ];
  export interface OutputObject {
    votingId: bigint;
    title: string;
    votingType: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface VotingSystem extends BaseContract {
  connect(runner?: ContractRunner | null): VotingSystem;
  waitForDeployment(): Promise<this>;

  interface: VotingSystemInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addAdmin: TypedContractMethod<[_admin: AddressLike], [void], "nonpayable">;

  "addAdmin(address)": TypedContractMethod<
    [_admin: AddressLike],
    [void],
    "nonpayable"
  >;

  addVoter: TypedContractMethod<[_voter: AddressLike], [void], "nonpayable">;

  "addVoter(address)": TypedContractMethod<
    [_voter: AddressLike],
    [void],
    "nonpayable"
  >;

  admins: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  "admins(address)": TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  chairman: TypedContractMethod<[], [string], "view">;

  "chairman()": TypedContractMethod<[], [string], "view">;

  createVoting: TypedContractMethod<
    [
      _title: string,
      _startTime: BigNumberish,
      _endTime: BigNumberish,
      _votingType: BigNumberish,
      _metaCID: BytesLike,
      _propositions: BytesLike[]
    ],
    [void],
    "nonpayable"
  >;

  "createVoting(string,uint256,uint256,uint8,bytes32,bytes32[])": TypedContractMethod<
    [
      _title: string,
      _startTime: BigNumberish,
      _endTime: BigNumberish,
      _votingType: BigNumberish,
      _metaCID: BytesLike,
      _propositions: BytesLike[]
    ],
    [void],
    "nonpayable"
  >;

  getActiveVotings: TypedContractMethod<
    [page: BigNumberish, perPage: BigNumberish],
    [
      [VotingInfoStructOutput[], bigint] & {
        votingsInfo: VotingInfoStructOutput[];
        totalActive: bigint;
      }
    ],
    "view"
  >;

  "getActiveVotings(uint256,uint256)": TypedContractMethod<
    [page: BigNumberish, perPage: BigNumberish],
    [
      [VotingInfoStructOutput[], bigint] & {
        votingsInfo: VotingInfoStructOutput[];
        totalActive: bigint;
      }
    ],
    "view"
  >;

  getCompletedVotings: TypedContractMethod<
    [page: BigNumberish, perPage: BigNumberish],
    [
      [VotingInfoStructOutput[], bigint] & {
        votingsInfo: VotingInfoStructOutput[];
        totalCompleted: bigint;
      }
    ],
    "view"
  >;

  "getCompletedVotings(uint256,uint256)": TypedContractMethod<
    [page: BigNumberish, perPage: BigNumberish],
    [
      [VotingInfoStructOutput[], bigint] & {
        votingsInfo: VotingInfoStructOutput[];
        totalCompleted: bigint;
      }
    ],
    "view"
  >;

  getIncomingVotings: TypedContractMethod<
    [page: BigNumberish, perPage: BigNumberish],
    [
      [VotingInfoStructOutput[], bigint] & {
        votingsInfo: VotingInfoStructOutput[];
        totalIncoming: bigint;
      }
    ],
    "view"
  >;

  "getIncomingVotings(uint256,uint256)": TypedContractMethod<
    [page: BigNumberish, perPage: BigNumberish],
    [
      [VotingInfoStructOutput[], bigint] & {
        votingsInfo: VotingInfoStructOutput[];
        totalIncoming: bigint;
      }
    ],
    "view"
  >;

  getPropositions: TypedContractMethod<
    [votingId: BigNumberish],
    [string[]],
    "view"
  >;

  "getPropositions(uint256)": TypedContractMethod<
    [votingId: BigNumberish],
    [string[]],
    "view"
  >;

  getRole: TypedContractMethod<[_addr: AddressLike], [string], "view">;

  "getRole(address)": TypedContractMethod<
    [_addr: AddressLike],
    [string],
    "view"
  >;

  getVoting: TypedContractMethod<
    [id: BigNumberish],
    [VotingInfoStructOutput],
    "view"
  >;

  "getVoting(uint256)": TypedContractMethod<
    [id: BigNumberish],
    [VotingInfoStructOutput],
    "view"
  >;

  getVotingBatch: TypedContractMethod<
    [ids: BigNumberish[]],
    [[string[], string[][]] & { titles: string[]; cids: string[][] }],
    "view"
  >;

  "getVotingBatch(uint256[])": TypedContractMethod<
    [ids: BigNumberish[]],
    [[string[], string[][]] & { titles: string[]; cids: string[][] }],
    "view"
  >;

  getVotingHistory: TypedContractMethod<
    [user: AddressLike, page: BigNumberish, perPage: BigNumberish],
    [
      [VotingSystem.VotingInfoWithChoiceStructOutput[], bigint] & {
        userVotingsInfoWithChoice: VotingSystem.VotingInfoWithChoiceStructOutput[];
        totalVotings: bigint;
      }
    ],
    "view"
  >;

  "getVotingHistory(address,uint256,uint256)": TypedContractMethod<
    [user: AddressLike, page: BigNumberish, perPage: BigNumberish],
    [
      [VotingSystem.VotingInfoWithChoiceStructOutput[], bigint] & {
        userVotingsInfoWithChoice: VotingSystem.VotingInfoWithChoiceStructOutput[];
        totalVotings: bigint;
      }
    ],
    "view"
  >;

  getVotingStats: TypedContractMethod<
    [_votingId: BigNumberish],
    [
      [bigint, bigint, bigint[]] & {
        totalVoters: bigint;
        votesCast: bigint;
        propositionVotes: bigint[];
      }
    ],
    "view"
  >;

  "getVotingStats(uint256)": TypedContractMethod<
    [_votingId: BigNumberish],
    [
      [bigint, bigint, bigint[]] & {
        totalVoters: bigint;
        votesCast: bigint;
        propositionVotes: bigint[];
      }
    ],
    "view"
  >;

  getVotingStatus: TypedContractMethod<
    [_votingId: BigNumberish],
    [string],
    "view"
  >;

  "getVotingStatus(uint256)": TypedContractMethod<
    [_votingId: BigNumberish],
    [string],
    "view"
  >;

  removeAdmin: TypedContractMethod<[_admin: AddressLike], [void], "nonpayable">;

  "removeAdmin(address)": TypedContractMethod<
    [_admin: AddressLike],
    [void],
    "nonpayable"
  >;

  removeVoter: TypedContractMethod<[_voter: AddressLike], [void], "nonpayable">;

  "removeVoter(address)": TypedContractMethod<
    [_voter: AddressLike],
    [void],
    "nonpayable"
  >;

  vote: TypedContractMethod<
    [_votingId: BigNumberish, _propositionIndex: BigNumberish],
    [void],
    "nonpayable"
  >;

  "vote(uint256,uint256)": TypedContractMethod<
    [_votingId: BigNumberish, _propositionIndex: BigNumberish],
    [void],
    "nonpayable"
  >;

  voters: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  "voters(address)": TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  votingCount: TypedContractMethod<[], [bigint], "view">;

  "votingCount()": TypedContractMethod<[], [bigint], "view">;

  votings: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, bigint, bigint, bigint, string, boolean] & {
        id: bigint;
        title: string;
        startTime: bigint;
        endTime: bigint;
        votingType: bigint;
        metaCID: string;
        exists: boolean;
      }
    ],
    "view"
  >;

  "votings(uint256)": TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, bigint, bigint, bigint, string, boolean] & {
        id: bigint;
        title: string;
        startTime: bigint;
        endTime: bigint;
        votingType: bigint;
        metaCID: string;
        exists: boolean;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addAdmin"
  ): TypedContractMethod<[_admin: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "addAdmin(address)"
  ): TypedContractMethod<[_admin: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "addVoter"
  ): TypedContractMethod<[_voter: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "addVoter(address)"
  ): TypedContractMethod<[_voter: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "admins"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "admins(address)"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "chairman"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "chairman()"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "createVoting"
  ): TypedContractMethod<
    [
      _title: string,
      _startTime: BigNumberish,
      _endTime: BigNumberish,
      _votingType: BigNumberish,
      _metaCID: BytesLike,
      _propositions: BytesLike[]
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createVoting(string,uint256,uint256,uint8,bytes32,bytes32[])"
  ): TypedContractMethod<
    [
      _title: string,
      _startTime: BigNumberish,
      _endTime: BigNumberish,
      _votingType: BigNumberish,
      _metaCID: BytesLike,
      _propositions: BytesLike[]
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getActiveVotings"
  ): TypedContractMethod<
    [page: BigNumberish, perPage: BigNumberish],
    [
      [VotingInfoStructOutput[], bigint] & {
        votingsInfo: VotingInfoStructOutput[];
        totalActive: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getActiveVotings(uint256,uint256)"
  ): TypedContractMethod<
    [page: BigNumberish, perPage: BigNumberish],
    [
      [VotingInfoStructOutput[], bigint] & {
        votingsInfo: VotingInfoStructOutput[];
        totalActive: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getCompletedVotings"
  ): TypedContractMethod<
    [page: BigNumberish, perPage: BigNumberish],
    [
      [VotingInfoStructOutput[], bigint] & {
        votingsInfo: VotingInfoStructOutput[];
        totalCompleted: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getCompletedVotings(uint256,uint256)"
  ): TypedContractMethod<
    [page: BigNumberish, perPage: BigNumberish],
    [
      [VotingInfoStructOutput[], bigint] & {
        votingsInfo: VotingInfoStructOutput[];
        totalCompleted: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getIncomingVotings"
  ): TypedContractMethod<
    [page: BigNumberish, perPage: BigNumberish],
    [
      [VotingInfoStructOutput[], bigint] & {
        votingsInfo: VotingInfoStructOutput[];
        totalIncoming: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getIncomingVotings(uint256,uint256)"
  ): TypedContractMethod<
    [page: BigNumberish, perPage: BigNumberish],
    [
      [VotingInfoStructOutput[], bigint] & {
        votingsInfo: VotingInfoStructOutput[];
        totalIncoming: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getPropositions"
  ): TypedContractMethod<[votingId: BigNumberish], [string[]], "view">;
  getFunction(
    nameOrSignature: "getPropositions(uint256)"
  ): TypedContractMethod<[votingId: BigNumberish], [string[]], "view">;
  getFunction(
    nameOrSignature: "getRole"
  ): TypedContractMethod<[_addr: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "getRole(address)"
  ): TypedContractMethod<[_addr: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "getVoting"
  ): TypedContractMethod<[id: BigNumberish], [VotingInfoStructOutput], "view">;
  getFunction(
    nameOrSignature: "getVoting(uint256)"
  ): TypedContractMethod<[id: BigNumberish], [VotingInfoStructOutput], "view">;
  getFunction(
    nameOrSignature: "getVotingBatch"
  ): TypedContractMethod<
    [ids: BigNumberish[]],
    [[string[], string[][]] & { titles: string[]; cids: string[][] }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getVotingBatch(uint256[])"
  ): TypedContractMethod<
    [ids: BigNumberish[]],
    [[string[], string[][]] & { titles: string[]; cids: string[][] }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getVotingHistory"
  ): TypedContractMethod<
    [user: AddressLike, page: BigNumberish, perPage: BigNumberish],
    [
      [VotingSystem.VotingInfoWithChoiceStructOutput[], bigint] & {
        userVotingsInfoWithChoice: VotingSystem.VotingInfoWithChoiceStructOutput[];
        totalVotings: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getVotingHistory(address,uint256,uint256)"
  ): TypedContractMethod<
    [user: AddressLike, page: BigNumberish, perPage: BigNumberish],
    [
      [VotingSystem.VotingInfoWithChoiceStructOutput[], bigint] & {
        userVotingsInfoWithChoice: VotingSystem.VotingInfoWithChoiceStructOutput[];
        totalVotings: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getVotingStats"
  ): TypedContractMethod<
    [_votingId: BigNumberish],
    [
      [bigint, bigint, bigint[]] & {
        totalVoters: bigint;
        votesCast: bigint;
        propositionVotes: bigint[];
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getVotingStats(uint256)"
  ): TypedContractMethod<
    [_votingId: BigNumberish],
    [
      [bigint, bigint, bigint[]] & {
        totalVoters: bigint;
        votesCast: bigint;
        propositionVotes: bigint[];
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getVotingStatus"
  ): TypedContractMethod<[_votingId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getVotingStatus(uint256)"
  ): TypedContractMethod<[_votingId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "removeAdmin"
  ): TypedContractMethod<[_admin: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "removeAdmin(address)"
  ): TypedContractMethod<[_admin: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "removeVoter"
  ): TypedContractMethod<[_voter: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "removeVoter(address)"
  ): TypedContractMethod<[_voter: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "vote"
  ): TypedContractMethod<
    [_votingId: BigNumberish, _propositionIndex: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "vote(uint256,uint256)"
  ): TypedContractMethod<
    [_votingId: BigNumberish, _propositionIndex: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "voters"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "voters(address)"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "votingCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "votingCount()"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "votings"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, bigint, bigint, bigint, string, boolean] & {
        id: bigint;
        title: string;
        startTime: bigint;
        endTime: bigint;
        votingType: bigint;
        metaCID: string;
        exists: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "votings(uint256)"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, string, bigint, bigint, bigint, string, boolean] & {
        id: bigint;
        title: string;
        startTime: bigint;
        endTime: bigint;
        votingType: bigint;
        metaCID: string;
        exists: boolean;
      }
    ],
    "view"
  >;

  getEvent(
    key: "VoteCast"
  ): TypedContractEvent<
    VoteCastEvent.InputTuple,
    VoteCastEvent.OutputTuple,
    VoteCastEvent.OutputObject
  >;
  getEvent(
    key: "VoteCast(address,uint256,uint256)"
  ): TypedContractEvent<
    VoteCast_address_uint256_uint256_Event.InputTuple,
    VoteCast_address_uint256_uint256_Event.OutputTuple,
    VoteCast_address_uint256_uint256_Event.OutputObject
  >;
  getEvent(
    key: "VotingCreated"
  ): TypedContractEvent<
    VotingCreatedEvent.InputTuple,
    VotingCreatedEvent.OutputTuple,
    VotingCreatedEvent.OutputObject
  >;
  getEvent(
    key: "VotingCreated(uint256,string,uint8)"
  ): TypedContractEvent<
    VotingCreated_uint256_string_uint8_Event.InputTuple,
    VotingCreated_uint256_string_uint8_Event.OutputTuple,
    VotingCreated_uint256_string_uint8_Event.OutputObject
  >;

  filters: {
    "VoteCast(address,uint256,uint256)": TypedContractEvent<
      VoteCastEvent.InputTuple,
      VoteCastEvent.OutputTuple,
      VoteCastEvent.OutputObject
    >;
    VoteCast: TypedContractEvent<
      VoteCastEvent.InputTuple,
      VoteCastEvent.OutputTuple,
      VoteCastEvent.OutputObject
    >;

    "VotingCreated(uint256,string,uint8)": TypedContractEvent<
      VotingCreatedEvent.InputTuple,
      VotingCreatedEvent.OutputTuple,
      VotingCreatedEvent.OutputObject
    >;
    VotingCreated: TypedContractEvent<
      VotingCreatedEvent.InputTuple,
      VotingCreatedEvent.OutputTuple,
      VotingCreatedEvent.OutputObject
    >;
  };
}
